name: Build infernoFSPatcher
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++
      - name: Configure and Build
        run: |
          # الانتقال إلى المجلد الذي يحتوي على CMakeLists.txt
          cd infernofspatcher
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: inferno_fs_patcher
          path: infernofspatcher/build/inferno_fs_patcher
